name: Locked
version: 1.1.0
main: fr.ftnl.locked.Locked
description: Bloqué dans votre chunk seul vos exploits vous libéreront
author: ocelus
website: https://ftnl.fr
api-version: '1.21.4'

commands:
  reset:
    description: Reset.
    usage: /<command>
    permission: "locked.permission.reset"
  change-border:
    description: Augmente la bordure de la taille indiqué
    usage: /<command> <size>
    permission: "locked.permission.change-border"